import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Footer } from "@/components/sections";
import HeaderWrapper from "@/components/sections/header/HeaderWrapper";
import { HeaderThemeProvider } from "@/contexts/HeaderThemeContext";
import {NextIntlClientProvider} from 'next-intl';
import "@/styles/index.scss";
import '@/styles/root.scss';

const geistInter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={geistInter.variable}>
        <HeaderThemeProvider>
          <NextIntlClientProvider>
            <HeaderWrapper/>
            <main className="main">
              {children}
            </main>
            <Footer/>
          </NextIntlClientProvider>
        </HeaderThemeProvider>
      </body>
    </html>
  );
}
